//Config file to call required ipfs variables via the web3 script.
//The web3 script is used to communicate with Metamask.
import web3 from './web3';

//This is the contract address which is generated by remix.io
//on the successful compilation fof the ASTER contract.
const address = '0xcf9bbd6ce12aea65653226ce44ac6ba76ed8e40f';
//This section sets the const variable "abi" to the abi data generated
//from the ASTER contract compilation.
const abi = [
    {
        "constant": false,
        "inputs": [
            {
                "name": "x",
                "type": "string"
            }
        ],
        "name": "sendA",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "y",
                "type": "string"
            }
        ],
        "name": "sendB",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "constant": false,
        "inputs": [
            {
                "name": "z",
                "type": "string"
            }
        ],
        "name": "sendC",
        "outputs": [],
        "payable": false,
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "constant": true,
        "inputs": [],
        "name": "getA",
        "outputs": [
            {
                "name": "x",
                "type": "string"
            }
        ],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
    },
    {
        "constant": true,
        "inputs": [],
        "name": "getB",
        "outputs": [
            {
                "name": "y",
                "type": "string"
            }
        ],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
    },
    {
        "constant": true,
        "inputs": [],
        "name": "getC",
        "outputs": [
            {
                "name": "z",
                "type": "string"
            }
        ],
        "payable": false,
        "stateMutability": "view",
        "type": "function"
    }
]
export default new web3.eth.Contract(abi, address);